import type { Metadata } from 'next';
import { Bellefair, Barlow_Condensed, Barlow } from 'next/font/google';
import './globals.css';

const bellefair = Bellefair({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bellefair',
});
const barlow_condensed = Barlow_Condensed({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-barlow-condensed',
});
const barlow = Barlow({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-barlow',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
